model_name: fdivergence
dataset_name: cifar10
dataset_args:
  data_dir: ../data/cifar10
  noise_rate: 0.6
  noise_type: instance
  batch_size: 128
model_args:
  initial_lr: 0.1 # TODO: sometimes different initial_lr is used
  momentum: 0.9
  weight_decay: 0.0005 # 5e-4
  divergence: "Total-Variation"
  warmup_epochs: 120
trainer_args:
  max_epochs: 100
seed: 0
