model_name: FBT
dataset_name: noisylabels
dataset_args:
  dataset_name: cifar10
  noise_type: "random_label1"
  batch_size: 128
model_args:
  loss_type: "forward"
  n_warmup_epochs: 100
  initial_lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
trainer_args:
  max_epochs: 200
seed: 1337