classifier: resnet34
classifier_args:
  weights: null
  num_classes: 10

strategy: cores2
strategy_args:
  initial_lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

datamodule: noise
datamodule_args:
  noise: symmetric
  noise_args:
    num_classes: 10
    noise_rate: 0.2
  batch_size: 128
  num_workers: 2

dataset: cifar10
dataset_args:
  root: ../data/cifar
train_dataset_args:
  transform: cifar10-train
val_dataset_args:
  train: False
  transform: cifar10-test

trainer_args:
  max_epochs: 100
seed: 1337
