from .CAL import CAL_config
from .CE import CE_config
from .co_teaching import co_teaching_config
from .co_teaching_plus import co_teaching_plus_config
from .cores2 import cores2_config
from .divide_mix import divide_mix_config
from .ELR import ELR_config
from .ELR_plus import ELR_plus_config
#from .forward_T import ...
#from .backward_T import ...
from .GCE import GCE_config
from .jocor import jocor_config
#from .peer_loss import ...
from .PES import PES_config
from .PES_semi import PES_semi_config
from .SOP import SOP_config
from .SOP_plus import SOP_plus_config
#from .T_revision import ...
from .volminnet import volminnet_config